### ISSUE TITLE
an error occurred. Cannot read property 'chat' of undefined

### ISSUE THREAD

**Issue by downright770** [lgaticaq/hubot-wikipedia-lang#8]
Hi,
I'm running the matteruser adapter for Mattermost and seeing if I can get your script running.
I can pull the list of demands to hubot in Mattermost, able to change language if needed but when running a search I get back "an error occurred. Cannot read property 'chat' of undefined". 

I'm running the bot through a shell script, but far as I know you don't need to do anything there for external scripts.

**Comment by lgaticaq** [comment]
Hi,
The script was adapted to use slack attachments. This is why this causes errors in other apps (Mattermost). Anyway it's easy to add the exception to work in other apps. As soon as I have available time I update the script.
regards

**Comment by downright770** [comment]
Okay thanks for getting back

**Comment by lgaticaq** [comment]
@downright770 fix in version 1.0.3 :+1:
